version: "3.9"

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      start_period: 40s
      interval: 5s
      timeout: 5s
      retries: 8
    networks:
      - inatel

  stock-manager:
    image: adautomendes/stock-manager
    container_name: stock-manager
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/stock || exit 1
      start_period: 40s
      interval: 5s
      timeout: 5s
      retries: 8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inatel

  quotation-management:
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        JAR_FILE: target/quotation-management-0.0.1-SNAPSHOT.jar
    image: quotation-management
    container_name: quotation-management
    ports:
      - 8081:8081
    environment:
      - SERVER_HOST=quotation-management
      - SERVER_PORT=8081
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - STOCK_MANAGER_HOST=stock-manager
      - STOCK_MANAGER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      stock-manager:
        condition: service_healthy
    networks:
      - inatel

networks:
  inatel:
    driver: bridge
