version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    volumes:
      - /c/Users/Paulera/Documents/Trampo Inatel/Projeto 1/quotation-management/.init/create-database.sql
    networks:
      - inatel

  stock-manager:
    image: adautomendes/stock-manager
    container_name: stock-manager
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - inatel

  quotation-management:
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        JAR_FILE: target/quotation-management-0.0.1-SNAPSHOT.jar
    image: quotation-management
    container_name: quotation-management
    ports:
      - 8081:8081
    environment:
      - SERVER_HOST=quotation-management
      - SERVER_PORT=8081
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - STOCK_MANAGER_HOST=stock-manager
      - STOCK_MANAGER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - stock-manager
      - mysql
    networks:
      - inatel

networks:
  inatel:
    driver: bridge
